### ISSUE TITLE
Swapping

### ISSUE THREAD

**Issue by michaelzixizhou** [KidneyOS/KidneyOS#95]
Swapping feature and a generic page eviction trait.

### TODO
- [x] Swap space struct with `swap_pagein` and `swap_pageout` functions.
- [x] Utilize swap partition from disk.
- [x] Add swap bit to PTE
- [x] Add generic trait page replacement policy.
- [ ] Add default random page eviction.
- [ ] Use `swap_pageout` and eviction algorithm in `KernelAllocator`.
- [ ] Figure out pages are accessed in memory
- [ ] Use `swap_pagein` on access to a page in swap.
